### PR TITLE
Issue 126: deprecate style only, style description only, and document only workflows

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
Addresses #126. This PR:
- Removes the use_* functions for [style only](https://github.com/nmfs-fish-tools/ghactions4r/blob/main/.github/workflows/style-r-code.yml), [style description only](https://github.com/nmfs-fish-tools/ghactions4r/blob/main/.github/workflows/style-description.yml), and [document only workflows](https://github.com/nmfs-fish-tools/ghactions4r/blob/main/.github/workflows/update-roxygen-docs.yml)
- Adds a warning to the reusable workflows that they will soon be defunct (removed).

Users of these reusable workflows should instead use the [doc-and-style-r reusable workflow](https://github.com/nmfs-fish-tools/ghactions4r/blob/main/.github/workflows/doc-and-style-r.yml), which can be set up using [`ghactions4r::use_style_and_document()`](https://nmfs-fish-tools.github.io/ghactions4r/reference/use_doc_and_style_r.html)

I think a remaining step that I should take would be to post an issue on repositories that are using this workflow, as I'm not sure the warnings are visible enough:
example of a warning

@iantaylor-NOAA would you be able to review this within the next week? If not, I can see if @kellijohnson-NOAA or @Bai-Li-NOAA are available.

### CODE REVIEW

**Review by iantaylor-NOAA — APPROVED** [review]
Looks good to me. Thanks for working on this @k-doering-NOAA.

I agree with the idea of posting issues on the repos that use those packages (shouldn't take long with boilerplate language).

The only question I have is whether it would be better to replace "will soon be deprecated" with something like "will be deprecated on 1 Oct 2024" (or whatever other specific date you want). 

Also, when you do deprecate the workflows, would it lead to a failed github action, or just no action taking place?

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA thanks so much for getting to this so quickly.

good point about adding a date! I'll make it December (unless @Bai-Li-NOAA is ok with removing them while I'm out, and I can let her pick the date :) )

I'm planning on just deleting the reusable workflows, which should cause the github actions to fail

I'll leave this open until I've posted on the repos that are using the workflows and the deprecation date has been added.

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA, sounds good. December is fine.
I just updated one of the repos by running `ghactions4r::use_r_cmd_check()`, `ghactions4r::use_doc_and_style_r()`, and deleting old files which only took about 2 minutes: https://github.com/pfmc-assessments/PEPtools/commit/10eddd1971d57c34229a88e1a4454cd89c164c57.

**Comment by k-doering-NOAA** [comment]
Opened PRs to replace style or document only workflows with style and document workflow on the following https://github.com/afsc-assessments/spmR, https://github.com/nmfs-fish-tools/projectstats, https://github.com/pfmc-assessments/PacFIN.Utilities, https://github.com/ss3sim/ss3sim, https://github.com/pfmc-assessments/nwfscSurvey, https://github.com/nmfs-fish-tools/r4MAS. Those were the only remaining repos using these workflows.

**Pull request merged**
