### PR TITLE
feat: add additional args to yaml files

### LINKED ISSUE #144: Add an input option in r-cmd-check workflow to let users include additional install arguments
### What is your question?

The new release of SS3 created some errors in github actions that (`../ss3: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by ../ss3)` @e-perl-NOAA seems to have solved by adding the missing library via the lines below in https://github.com/nmfs-ost/ss3-user-examples/commit/7173d5e83ffde4f3c9d04e44c6cf91bd3067cfd1 
```
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get install --only-upgrade libstdc++6
```
I'm getting the same error in {r4ss} in call-r-cmd-check, but I'm assuming that those lines would have to occur after the matrix_prep step and therefore can't just be added prior to calling the {ghactions4r} workflow.

@Bai-Li-NOAA and @e-perl-NOAA, do you have any guidance on how to sort this out?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Bai-Li-NOAA**
This PR addresses issue #144 

- update the following YAML files to support additional arguments on Windows, macOS, and Ubuntu: `.github/workflows/build-pkgdown.yml`, `.github/workflows/r-cmd-check.yml`, and `.github/workflows/update-pkgdown.yml`
- allow additional arguments to be specified after checking out the repo and before setting up R
- add a helper function `validate_additional_args()` to validate additional arguments for R functions
- add a helper function `add_args()` to include platform-specific additional arguments in a YAML file
- add `additional_args` to `use_r_cmd_check()`, `use_update_pkgdown()`, and `use_build_pkgdown()` to pass additional arguments to YAML files (e.g., `call_*.yml`)
- add unit and integration tests to verify the new feature

### CODE REVIEW

**Comment by Bai-Li-NOAA** [comment]
@e-perl-NOAA, could you review this pull request? I will do a final cleanup after the review before merging the changes into the main branch. 

Also, could you test the new feature using SS3 repos? For example:

- Copy and paste the following code chunk into the `call-r-cmd-check.yml` file. See an example [here](https://github.com/nmfs-fish-tools/ghactions4r/blob/add-additional-args-to-yaml/.github/workflows/call-r-cmd-check.yml)
```yaml
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/r-cmd-check.yml@add-additional-args-to-yaml
    # uses: nmfs-fish-tools/ghactions4r/.github/workflows/r-cmd-check.yml@main
    with:
      additional_args_ubuntu: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install --only-upgrade libstdc++6
```
- Use the R code below to modify the YAML file. See an example [here](https://github.com/nmfs-fish-tools/ghactions4r/blob/add-additional-args-to-yaml/R/use_r_workflows.R#L284C1-L294C5)
```r
use_update_pkgdown(
  workflow_name = "call-update-pkgdown.yml",
  additional_args = list(
    "ubuntu" = c(
      "sudo apt-get update",
      "sudo apt-get install -y libcurl4-openssl-dev",
      "sudo add-apt-repository ppa:ubuntu-toolchain-r/test",
      "sudo apt-get install --only-upgrade libstdc++6"
    )
  )
)
```
Let me know if you have any questions!

**Comment by e-perl-NOAA** [comment]
Okay, I just added things in the r4ss repo which calls these workflows. It will take awhile for the tests to run and confirm that they work but I will let you know when they do. The r function to update the workflow does work (at least for the ubuntu additions) though of course I did have to change the branch once added from main to this one so that it will work when the github actions are running right now.

**Comment by e-perl-NOAA** [comment]
Ummm, so I keep getting [this result](https://github.com/r4ss/r4ss/actions/runs/11937124943/workflow) which is weird because I'm pretty sure everything is right. Idk if this is just one of those situations (like many other things these days) where everything has decided to stop working properly or something else

**Comment by Bai-Li-NOAA** [comment]
@e-perl-NOAA, my bad! I gave the wrong branch name. The correct one is `add-additional-args-to-yaml`
```yaml
uses: nmfs-fish-tools/ghactions4r/.github/workflows/r-cmd-check.yml@add-additional-args-to-yaml
    # uses: nmfs-fish-tools/ghactions4r/.github/workflows/r-cmd-check.yml@main
```

**Comment by e-perl-NOAA** [comment]
Okay it's working in r4ss (there is a problem with the macos run but that's a me problem with gh and APIs and github enterprise with single sign on, not a you problem)!

**Comment by e-perl-NOAA** [comment]
@Bai-Li-NOAA would it be too much trouble to add an input for env portion to the r-cmd-check for me to test out? I might not be able to get it to do what I want it to and thus it may not matter in the end. This could also be done in another branch not associated with this PR.

**Comment by e-perl-NOAA** [comment]
The env is to try to deal with API calls to the mac github actions runner.

**Comment by Bai-Li-NOAA** [comment]
@e-perl-NOAA Feel free to add an input of env to test in this branch or another branch, either works for me. I am not entirely sure about the desired input format for env portion, but let me know the details of the user case if you would like me to work on it.

**Comment by e-perl-NOAA** [comment]
Actually nevermind on the env, it already uses it. It looks like macs will just always cause strife in my life.

**Review by e-perl-NOAA — APPROVED** [review]

**Comment by e-perl-NOAA** [comment]
I assume that you will re-run with spell check before you merge.

**Comment by e-perl-NOAA** [comment]
I tried adding it and then realized that you already had the GITHUB_TOKEN in there which is what I wanted to try. Its nothing for you to worry about.

**Comment by Bai-Li-NOAA** [comment]
@e-perl-NOAA, okay, thanks for the update! I will do a final cleanup, including fixing the spell check GHA, before merging the PR.

**Comment by Bai-Li-NOAA** [comment]
@e-perl-NOAA I have merged the PR. You might need to update some GHA workflows in the SS3 repositories. Let me know if you have any questions!

**Pull request merged**
